"use client";
import { useState } from "react";
import type { Trade } from "@/types/trade";
import { localIdeas, type Idea } from "@/lib/local-ideas";

export function IdeasPanel({ trade }: { trade: Trade }) {
  const [ideas, setIdeas] = useState<Idea[] | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [source, setSource] = useState<"local" | "claude" | null>(null);

  function loadLocal() {
    setIdeas(localIdeas(trade));
    setSource("local");
    setError(null);
  }

  async function loadClaude() {
    setBusy(true);
    setError(null);
    try {
      const res = await fetch("/api/ideas", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(trade),
      });
      if (!res.ok) {
        const j = await res.json().catch(() => ({}));
        throw new Error(j.error ?? `Claude ideas failed (${res.status})`);
      }
      const data = await res.json();
      setIdeas(data.ideas);
      setSource("claude");
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed");
      // Fall back to local rules so user still gets value
      setIdeas(localIdeas(trade));
      setSource("local");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="card space-y-3">
      <div className="flex items-center justify-between">
        <div>
          <div className="label">Ideas to consider</div>
          {source && (
            <div className="text-xs text-gray-500">
              {source === "claude" ? "Generated by Claude" : "Rules-based suggestions"}
            </div>
          )}
        </div>
        <div className="flex gap-2">
          <button onClick={loadLocal} className="rounded-lg px-3 py-1.5 text-sm">
            Quick ideas
          </button>
          <button onClick={loadClaude} disabled={busy} className="btn-primary rounded-lg px-3 py-1.5 text-sm">
            {busy ? "Thinking…" : "Ask Claude"}
          </button>
        </div>
      </div>
      {error && (
        <div className="text-xs text-loss">
          {error} (showing rules-based ideas instead)
        </div>
      )}
      {!ideas && !error && (
        <p className="text-sm text-gray-400">
          Get alternative structures or adjustments. <strong>Quick ideas</strong> uses local rules; <strong>Ask Claude</strong> calls the Anthropic API (needs ANTHROPIC_API_KEY).
        </p>
      )}
      {ideas && (
        <ul className="space-y-3">
          {ideas.map((it, i) => (
            <li key={i} className="rounded-lg border border-border p-3">
              <div className="flex items-center justify-between">
                <div className="font-semibold">{it.name}</div>
                <span className="rounded-md border border-border px-2 py-0.5 text-xs text-gray-300">
                  {it.bias}
                </span>
              </div>
              <p className="mt-1 text-sm text-gray-300">{it.thesis}</p>
              <div className="mt-2 text-xs text-gray-400">
                <pre className="font-mono whitespace-pre-wrap">
                  {typeof it.structure === "string" ? it.structure : JSON.stringify(it.structure, null, 2)}
                </pre>
              </div>
              <div className="mt-2 text-xs">
                <span className="text-gray-400">Tradeoffs: </span>
                <span>{it.tradeoffs}</span>
              </div>
              <div className="text-xs">
                <span className="text-gray-400">When: </span>
                <span>{it.whenToConsider}</span>
              </div>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
